variables:
  # Your GitLab Container Registry URL, auto‑injected:
  IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

stages:
  - build
  - deploy

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$IMAGE" .
    - docker push "$IMAGE"
  only:
    - branches

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Here you can pull & run your image, or trigger your Kubernetes/Swarm deploy."
  when: manual
  only:
    - main
